// src/presentation/settings/sections/TemplatesSection.tsx

import { useCallback, useEffect, useState } from 'react';

import { Toast } from '@presentation/components/ui/toast';
import { useFormatMessage } from '@presentation/hooks/useFormatMessage';
import { useToast } from '@presentation/hooks/useToast';
import type { TemplateConfig } from '@shared/types';

import { mergeTemplates, SYSTEM_TEMPLATES } from './templates/systemTemplates';
import { TemplateEditor } from './templates/TemplateEditor';
import { TemplateListRail } from './templates/TemplateListRail';
import type { TemplateView } from './templates/templateTypes';

/** Props for {@link TemplatesSection}. */
export interface TemplatesSectionProps {
  /** Persisted user templates from the settings store. Defaults to `[]`. */
  readonly templates?: readonly TemplateConfig[];
  /** Adds a new template (id generated by caller). */
  readonly onAdd?: (template: Omit<TemplateConfig, 'id'>) => Promise<void>;
  /** Removes the template identified by `id`. */
  readonly onRemove?: (id: string) => Promise<void>;
  /** Merges `changes` into the template identified by `id`. */
  readonly onUpdate?: (id: string, changes: Partial<TemplateConfig>) => Promise<void>;
}

const NOOP_ADD: (t: Omit<TemplateConfig, 'id'>) => Promise<void> = async () => undefined;
const NOOP_REMOVE: (id: string) => Promise<void> = async () => undefined;
const NOOP_UPDATE: (id: string, changes: Partial<TemplateConfig>) => Promise<void> = async () =>
  undefined;

const SEEDED_BODY = `# {{page.title}}

> Clipped {{ now | date("MMMM D, YYYY") }} from [{{page.domain}}]({{page.url}})

{{ content | markdown }}`;

const SEEDED_NOTE_NAME = '{{date}}-{{title|safe_name}}';

/** Returns the merged + sorted template list. */
function useMergedTemplates(userTemplates: readonly TemplateConfig[]): readonly TemplateView[] {
  return mergeTemplates(userTemplates);
}

/** Keeps selectedId valid as the list changes. */
function useSelectedId(
  merged: readonly TemplateView[],
): [string | null, (id: string | null) => void] {
  const defaultId = merged[0]?.id ?? null;
  const [selectedId, setSelectedId] = useState<string | null>(defaultId);

  useEffect(() => {
    if (!merged.find((t) => t.id === selectedId)) {
      setSelectedId(merged[0]?.id ?? null);
    }
  }, [merged, selectedId]);

  return [selectedId, setSelectedId];
}

/** Wires global keyboard shortcuts for the templates section. */
function useTemplateKeyboardShortcuts(onNew: () => void): void {
  useEffect(() => {
    const handler = (e: KeyboardEvent): void => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'n') {
        e.preventDefault();
        onNew();
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 'f') {
        e.preventDefault();
        document.querySelector<HTMLInputElement>('[placeholder="Filter templates…"]')?.focus();
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  });
}

/** Props for {@link EmptyState}. */
interface EmptyStateProps {
  readonly message: string;
}

/** Centered empty-state message shown when no templates exist. */
function EmptyState({ message }: EmptyStateProps) {
  return (
    <div
      data-testid="templates-section"
      style={{
        display: 'flex',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <p style={{ fontSize: 13, color: 'var(--wh-muted)' }}>{message}</p>
    </div>
  );
}

/** Props for {@link SplitPane}. */
interface SplitPaneProps {
  readonly merged: readonly TemplateView[];
  readonly selectedId: string | null;
  readonly selectedTemplate: TemplateView;
  readonly toast: ReturnType<typeof useToast>['toast'];
  readonly onSelect: (id: string | null) => void;
  readonly onNew: () => void;
  readonly onUpdate: (id: string, changes: Partial<TemplateConfig>) => Promise<void>;
  readonly onDuplicate: (id: string) => void;
  readonly onExport: () => void;
  readonly onDelete: (id: string) => void;
  readonly onDismiss: () => void;
}

/** Renders the list rail, editor pane, and toast overlay side by side. */
function SplitPane({
  merged,
  selectedId,
  selectedTemplate,
  toast,
  onSelect,
  onNew,
  onUpdate,
  onDuplicate,
  onExport,
  onDelete,
  onDismiss,
}: SplitPaneProps) {
  return (
    <div
      data-testid="templates-section"
      style={{ display: 'flex', height: '100%', overflow: 'hidden' }}
    >
      <TemplateListRail
        templates={merged}
        selectedId={selectedId}
        onSelect={onSelect}
        onNew={onNew}
      />
      <TemplateEditor
        key={selectedTemplate.id}
        template={selectedTemplate}
        onUpdate={onUpdate}
        onDuplicate={onDuplicate}
        onExport={onExport}
        onDelete={onDelete}
      />
      <Toast toast={toast} onDismiss={onDismiss} />
    </div>
  );
}

/** Builds the duplicate handler for a template by id. */
function useDuplicateHandler(
  merged: readonly TemplateView[],
  onAdd: (t: Omit<TemplateConfig, 'id'>) => Promise<void>,
): (id: string) => void {
  return useCallback(
    (id: string): void => {
      const source: TemplateView | undefined = merged.find((t) => t.id === id);
      if (!source) return;
      onAdd({
        name: `${source.name} (copy)`,
        frontmatterTemplate: source.frontmatterTemplate,
        bodyTemplate: source.bodyTemplate,
        noteNameTemplate: source.noteNameTemplate,
      }).catch(() => undefined);
    },
    [merged, onAdd],
  );
}

/** Arguments for {@link useDeleteHandler}. */
interface DeleteHandlerArgs {
  readonly merged: readonly TemplateView[];
  readonly onAdd: (t: Omit<TemplateConfig, 'id'>) => Promise<void>;
  readonly onRemove: (id: string) => Promise<void>;
  readonly showToast: ReturnType<typeof useToast>['show'];
}

/** Builds the delete handler that removes and shows an undo toast. */
function useDeleteHandler({
  merged,
  onAdd,
  onRemove,
  showToast,
}: DeleteHandlerArgs): (id: string) => void {
  return useCallback(
    (id: string): void => {
      const target: TemplateView | undefined = merged.find((t) => t.id === id);
      if (!target || target.isSystem) return;
      onRemove(id).catch(() => undefined);
      showToast({
        message: `"${target.name}" deleted`,
        undoLabel: 'Undo',
        onUndo: () => {
          onAdd({
            name: target.name,
            frontmatterTemplate: target.frontmatterTemplate,
            bodyTemplate: target.bodyTemplate,
            noteNameTemplate: target.noteNameTemplate,
          }).catch(() => undefined);
        },
      });
    },
    [merged, onAdd, onRemove, showToast],
  );
}

/** Pane props minus onUpdate (provided by the parent). */
type PartialPaneProps = Omit<SplitPaneProps, 'onUpdate'>;

/** Return value of {@link useTemplateSectionHandlers}. */
interface SectionHandlers {
  readonly selected: TemplateView | null;
  readonly paneProps: PartialPaneProps;
}

/** Builds the new-template callback. */
function useNewHandler(onAdd: (t: Omit<TemplateConfig, 'id'>) => Promise<void>): () => void {
  return useCallback((): void => {
    onAdd({
      name: 'Untitled template',
      frontmatterTemplate: '',
      bodyTemplate: SEEDED_BODY,
      noteNameTemplate: SEEDED_NOTE_NAME,
    }).catch(() => undefined);
  }, [onAdd]);
}

/** Owns all state and derived callbacks for {@link TemplatesSection}. */
function useTemplateSectionHandlers(
  templates: readonly TemplateConfig[],
  onAdd: (t: Omit<TemplateConfig, 'id'>) => Promise<void>,
  onRemove: (id: string) => Promise<void>,
): SectionHandlers {
  const merged = useMergedTemplates(templates);
  const [selectedId, setSelectedId] = useSelectedId(merged);
  const { toast, show: showToast, dismiss } = useToast();
  const handleNew = useNewHandler(onAdd);
  useTemplateKeyboardShortcuts(handleNew);
  const handleDuplicate = useDuplicateHandler(merged, onAdd);
  const handleDelete = useDeleteHandler({ merged, onAdd, onRemove, showToast });
  const handleExport = useCallback((): void => undefined, []);
  const selected = merged.find((t) => t.id === selectedId) ?? merged[0] ?? null;
  const paneProps: PartialPaneProps = {
    merged,
    selectedId,
    selectedTemplate: selected ?? merged[0] ?? ({} as TemplateView),
    toast,
    onSelect: setSelectedId,
    onNew: handleNew,
    onDuplicate: handleDuplicate,
    onExport: handleExport,
    onDelete: handleDelete,
    onDismiss: dismiss,
  };
  return { selected, paneProps };
}

/**
 * Root component for the Templates settings tab. Renders a 240px list rail
 * (system + user templates) alongside a full-height editor pane. System
 * templates are always visible and read-only; user templates come from the
 * settings store via `templates` prop.
 */
export function TemplatesSection({
  templates = [],
  onAdd = NOOP_ADD,
  onRemove = NOOP_REMOVE,
  onUpdate = NOOP_UPDATE,
}: TemplatesSectionProps) {
  const fmt = useFormatMessage();
  const { selected, paneProps } = useTemplateSectionHandlers(templates, onAdd, onRemove);
  if (!selected) {
    return (
      <EmptyState
        message={fmt({ id: 'settings.templates.empty', defaultMessage: 'No templates found.' })}
      />
    );
  }
  return <SplitPane {...paneProps} onUpdate={onUpdate} />;
}

export { SYSTEM_TEMPLATES };
