export const TYPES = {
  ITabAdapter: Symbol.for('ITabAdapter'),
  IStorageAdapter: Symbol.for('IStorageAdapter'),
  IRuntimeAdapter: Symbol.for('IRuntimeAdapter'),
  INotificationAdapter: Symbol.for('INotificationAdapter'),
  ICommandAdapter: Symbol.for('ICommandAdapter'),
  IContextMenuAdapter: Symbol.for('IContextMenuAdapter'),
  IActionAdapter: Symbol.for('IActionAdapter'),
  ISidePanelAdapter: Symbol.for('ISidePanelAdapter'),
  IClipboardAdapter: Symbol.for('IClipboardAdapter'),
  ILogger: Symbol.for('ILogger'),
  IPluginRegistry: Symbol.for('IPluginRegistry'),
  IHookSystem: Symbol.for('IHookSystem'),
  IUIRegistry: Symbol.for('IUIRegistry'),
  ISettingsStorage: Symbol.for('ISettingsStorage'),
  IDestinationStorage: Symbol.for('IDestinationStorage'),
  IClipService: Symbol.for('IClipService'),
  IHighlightService: Symbol.for('IHighlightService'),
  IReaderService: Symbol.for('IReaderService'),
  ISettingsService: Symbol.for('ISettingsService'),
  ITemplateService: Symbol.for('ITemplateService'),
} as const;
